# Generated by Django 5.2.17 on 2026-09-20 19:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import procurement.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. MOH, BPP, LGA-WUK', max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='MINISTRY', max_length=24)),
                ('lga', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'party_agency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received and sealed'), ('UNSEALED', 'Opened in public'), ('RESPONSIVE', 'Preliminary examination passed'), ('EVALUATED', 'Scores complete'), ('RECOMMENDED', 'Recommended for award'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn by bidder')], default='RECEIVED', max_length=12)),
                ('amount', procurement.models.MoneyField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('commitment_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('envelope_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('ciphertext_ref', models.CharField(blank=True, editable=False, max_length=300)),
                ('receipt_ref', models.CharField(editable=False, help_text="bidder's receipt number", max_length=40, unique=True)),
                ('late', models.BooleanField(default=False, editable=False)),
                ('price_schedule_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'proc_bid',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('kind', models.CharField(choices=[('PASSFAIL', 'Pass/fail (responsive)'), ('SCORED', 'Scored')], default='SCORED', max_length=8)),
                ('min_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('locked', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'proc_criterion',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('est_value', procurement.models.MoneyField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_awards', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proc_lot',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Platform administrator'), ('DG', 'Bureau Director-General'), ('PDE', 'Procurement unit (MDA)'), ('HEAD', 'Head of MDA'), ('EVALUATOR', 'Evaluation committee member'), ('APPROVER', 'Approving authority'), ('TREASURY', 'Finance / payment certification'), ('AUDITOR', 'Audit'), ('APPEALS', 'Independent appeals panel'), ('SUPPLIER', 'Registered supplier'), ('PUBLIC', 'Anonymous oversight (no login)')], default='PUBLIC', max_length=16)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('mfa_enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='procurement.agency')),
            ],
            options={
                'db_table': 'party_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RECOMMENDED', 'Recommended by committee'), ('APPROVED', 'Approved by authority'), ('PUBLISHED', 'Notice published'), ('OBJECTION', 'Under objection'), ('CONTRACTED', 'Contract signed'), ('VOID', 'Set aside')], default='RECOMMENDED', max_length=12)),
                ('amount', procurement.models.MoneyField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notice_ref', models.CharField(blank=True, max_length=80)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('objection_until', models.DateTimeField(blank=True, null=True)),
                ('non_lowest_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_approved', to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='procurement.bid')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.lot')),
            ],
            options={
                'db_table': 'proc_award',
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fy', models.CharField(db_index=True, max_length=9)),
                ('project_code', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source', models.CharField(default='STATE', max_length=40)),
                ('released', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('committed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='procurement.agency')),
            ],
            options={
                'db_table': 'fin_budget_line',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('SIGNED', 'Signed'), ('ACTIVE', 'Being performed'), ('ACCEPTED', 'Delivered and accepted'), ('PAID', 'Payment certified'), ('CLOSED', 'Closed out'), ('DEFAULTED', 'In default')], default='SIGNED', max_length=12)),
                ('value', procurement.models.MoneyField(decimal_places=2, max_digits=18)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_days', models.PositiveIntegerField()),
                ('advance_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('perf_guarantee_pct', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('defect_days', models.PositiveIntegerField(default=365)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('deliverables', models.TextField(blank=True)),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='procurement.award')),
            ],
            options={
                'db_table': 'proc_contract',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=60, unique=True)),
                ('value', procurement.models.MoneyField(decimal_places=2, max_digits=18)),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_sha256', models.CharField(blank=True, max_length=64)),
                ('certified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances_signed', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='procurement.contract')),
            ],
            options={
                'db_table': 'proc_acceptance',
            },
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MILESTONE', 'Milestone'), ('VARIATION', 'Variation'), ('CLAIM', 'Claim'), ('ADVANCE', 'Advance'), ('GUARANTEE', 'Guarantee'), ('SNAG', 'Defects'), ('NOTE', 'Note')], max_length=12)),
                ('amount', procurement.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('note', models.TextField()),
                ('occurred_at', models.DateField(default=django.utils.timezone.localdate)),
                ('published', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='procurement.contract')),
            ],
            options={
                'db_table': 'proc_contract_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='procurement.lot'),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('COMPANY', 'Limited liability company'), ('BUSINESS_NAME', 'Business name / sole proprietor'), ('PARTNERSHIP', 'Partnership'), ('COOPERATIVE', 'Cooperative'), ('JV', 'Joint venture (lead partner)')], default='COMPANY', max_length=14)),
                ('legal_name', models.CharField(db_index=True, max_length=250)),
                ('rc_number', models.CharField(blank=True, help_text='CAC RC/GT number, e.g. RC1234567', max_length=20)),
                ('tin', models.CharField(blank=True, help_text='FIRS TIN, 8 digits + dash + 4', max_length=20)),
                ('ubn', models.CharField(blank=True, help_text='Taxation Reform Act UBN, when issued', max_length=20)),
                ('pencom', models.CharField(blank=True, help_text='PenCom pension certificate ref', max_length=40)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=24)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(default='Taraba', max_length=40)),
                ('lga', models.CharField(blank=True, max_length=60)),
                ('scope', models.CharField(choices=[('LOCAL', 'Taraba-domiciled'), ('NATIONAL', 'Nigerian, outside Taraba')], default='LOCAL', max_length=8)),
                ('category', models.CharField(choices=[('A', 'Category A — Works (major)'), ('B', 'Category B — Goods'), ('C', 'Category C — Services / consultancy'), ('D', 'Category D — ICT')], default='B', max_length=1)),
                ('year_incorporated', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bo_declared', models.BooleanField(default=False, help_text='beneficial ownership disclosed')),
                ('pep_flag', models.BooleanField(default=False, help_text='politically exposed person among owners')),
                ('is_active', models.BooleanField(default=True)),
                ('debarred_from', models.DateField(blank=True, null=True)),
                ('debarred_to', models.DateField(blank=True, null=True)),
                ('debarment_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'party_supplier',
                'ordering': ['legal_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('rc_number', ''), _negated=True), ('is_active', False), _connector='OR'), name='supplier_needs_rc'), models.CheckConstraint(condition=models.Q(models.Q(('tin', ''), _negated=True), ('is_active', False), _connector='OR'), name='supplier_needs_tin')],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='procurement.party'),
        ),
        migrations.CreateModel(
            name='PartyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=250)),
                ('owner_rc_number', models.CharField(blank=True, help_text='if the owner is itself a company', max_length=20)),
                ('owner_nin_hash', models.CharField(blank=True, help_text='hash only; never store NIN in clear', max_length=64)),
                ('pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_pep', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='procurement.party')),
            ],
            options={
                'db_table': 'party_ownership',
            },
        ),
        migrations.CreateModel(
            name='PaymentCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('amount', procurement.models.MoneyField(decimal_places=2, max_digits=18)),
                ('certified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('treasury_ref', models.CharField(blank=True, max_length=60)),
                ('acceptance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certification', to='procurement.acceptancecertificate')),
                ('certified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications_made', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='procurement.contract')),
            ],
            options={
                'db_table': 'proc_payment_cert',
            },
        ),
        migrations.CreateModel(
            name='RelatedPartyDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(help_text='free text, published verbatim', max_length=250)),
                ('named_official', models.CharField(blank=True, max_length=250)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='procurement.party')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'party_declaration',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('narrative', models.TextField()),
                ('scored_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='procurement.bid')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='procurement.criterion')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proc_score',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocid', models.CharField(blank=True, editable=False, max_length=60, unique=True)),
                ('reference', models.CharField(blank=True, help_text='internal MDA ref, shown alongside ocid', max_length=60)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (not yet public)'), ('PUBLISHED', 'Published / open for bids'), ('CLARIFYING', 'Clarification window'), ('CLOSED', 'Submissions closed, sealed'), ('OPENED', 'Public bid opening done'), ('EVALUATING', 'Under evaluation'), ('AWARDED', 'Award recommended / published'), ('CONTRACTED', 'Contract signed'), ('FROZEN', 'Frozen by objection (Georgia mechanism)'), ('TERMINATED', 'Terminated without award'), ('CANCELLED', 'Cancelled before publication')], db_index=True, default='DRAFT', max_length=18)),
                ('method', models.CharField(choices=[('ICB', 'International competitive bidding'), ('NCB', 'National competitive bidding'), ('RFQ', 'Request for quotations'), ('SHOP', 'Shopping / market survey'), ('DIRECT', 'Direct procurement'), ('CATALOGUE', 'Catalogue fast-lane'), ('TWO_STAGE', 'Two-stage bidding'), ('RESTRICTED', 'Restricted bidding')], max_length=12)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('est_value', procurement.models.MoneyField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='published estimate')),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('total_value', procurement.models.MoneyField(blank=True, decimal_places=2, help_text='sum of awarded lots; derived', max_digits=18, null=True)),
                ('approval_body', models.CharField(blank=True, max_length=40)),
                ('no_objection_ref', models.CharField(blank=True, help_text='BPP/Agency certificate ref where required', max_length=80)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('qa_close_at', models.DateTimeField(blank=True, null=True)),
                ('submission_close_at', models.DateTimeField(blank=True, null=True)),
                ('opening_at', models.DateTimeField(blank=True, null=True)),
                ('opening_venue', models.CharField(blank=True, default='BPP conference hall, Jalingo', max_length=200)),
                ('bid_security_amount', procurement.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('immutable_from', models.DateTimeField(blank=True, editable=False, null=True)),
                ('frozen_until', models.DateTimeField(blank=True, help_text='Georgia mechanism: 10-day stakeholder freeze', null=True)),
                ('commitment_root', models.CharField(blank=True, editable=False, help_text='Merkle root of all bid commitments', max_length=64)),
                ('reserved_for_local_pct', models.PositiveSmallIntegerField(default=0)),
                ('sme_set_aside_pct', models.PositiveSmallIntegerField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='procurement.agency')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='procurement.budgetline')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proc_tender',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filed_by_label', models.CharField(blank=True, help_text="published identity (or 'anonymous')", max_length=200)),
                ('ground', models.TextField()),
                ('panel_members', models.JSONField(default=list, help_text='[{name, nominator: CSO|GOV}] — published')),
                ('decision', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('PENDING', 'Awaiting panel'), ('DISMISSED', 'Dismissed'), ('UPHELD', 'Upheld — award set aside'), ('REMEDIED', 'Upheld in part — remedy ordered')], default='PENDING', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_until', models.DateTimeField(blank=True, null=True)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='procurement.award')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_objection',
                'ordering': ['-filed_at'],
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='procurement.tender'),
        ),
        migrations.CreateModel(
            name='EvaluationCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='MEMBER', max_length=40)),
                ('formed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('declaration_sha256', models.CharField(blank=True, help_text='signed conflict-of-interest declaration', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_evaluation_committee',
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='procurement.tender'),
        ),
        migrations.AddField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='procurement.tender'),
        ),
        migrations.AddField(
            model_name='award',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='procurement.tender'),
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='SOLICITATION', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=250)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('obj_key', models.CharField(help_text='private object-store key; never a public URL', max_length=300)),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, help_text='why this version exists (addendum reason), published verbatim')),
                ('upload_deadline_effect', models.BooleanField(default=False, help_text='true if this version extended the deadline')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='procurement.tenderdocument')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_tender_document',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PartyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CAC', 'Corporate affairs (CAC registry)'), ('TIN', 'Tax identification (FIRS)'), ('PENSION', 'PenCom certificate'), ('BANK', 'NUBAN account-name match'), ('BO', 'Beneficial ownership'), ('DEBARMENT', 'Debarment/exclusion screening'), ('CAPABILITY', 'Technical and financial capability')], max_length=12)),
                ('status', models.CharField(default='PENDING', max_length=7)),
                ('reference', models.CharField(blank=True, help_text='registry receipt / search ref', max_length=120)),
                ('evidence_sha256', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, help_text='e.g. tax clearance year-end', null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='procurement.party')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_made', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.tenderdocument')),
            ],
            options={
                'db_table': 'party_verification',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asked_by_anonymous', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('extends_deadline', models.BooleanField(default=False)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_tender_question',
                'ordering': ['asked_at'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(db_index=True, help_text='e.g. 2026 or 2026/2027', max_length=9)),
                ('method', models.CharField(choices=[('ICB', 'International competitive bidding'), ('NCB', 'National competitive bidding'), ('RFQ', 'Request for quotations'), ('SHOP', 'Shopping / market survey'), ('DIRECT', 'Direct procurement'), ('CATALOGUE', 'Catalogue fast-lane'), ('TWO_STAGE', 'Two-stage bidding'), ('RESTRICTED', 'Restricted bidding')], max_length=12)),
                ('goods', models.CharField(default='GENERIC', max_length=16)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='null = open ended', max_digits=18, null=True)),
                ('approval_body', models.CharField(help_text='e.g. ACCOUNTING_OFFICER, MTB, BPP_NO_OBJECTION, FEC', max_length=40)),
                ('min_advert_days', models.PositiveSmallIntegerField(default=14, help_text='Lagos/Nigeria rule: >= 2 weeks for competitive bidding')),
                ('bid_security_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='PPA s.26(1): not more than 2%', max_digits=5)),
                ('min_quotations', models.PositiveSmallIntegerField(default=1, help_text='RFQ: at least 3 unrelated suppliers')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rule_threshold',
                'ordering': ['-fy', 'method', 'min_amount'],
                'constraints': [models.UniqueConstraint(fields=('fy', 'method', 'goods', 'min_amount'), name='uniq_threshold_band'), models.CheckConstraint(condition=models.Q(('min_amount__gte', Decimal('0'))), name='threshold_non_negative')],
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='procurement.thresholdrule'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['fy', 'agency'], name='budget_fy_agency_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('fy', 'agency', 'project_code'), name='uniq_budget_line'),
        ),
        migrations.AddConstraint(
            model_name='partyownership',
            constraint=models.CheckConstraint(condition=models.Q(('pct__gt', Decimal('0')), ('pct__lte', Decimal('100'))), name='owner_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='partyownership',
            constraint=models.UniqueConstraint(fields=('party', 'owner_name'), name='uniq_owner_per_party'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('bid', 'criterion'), name='uniq_score_per_criterion'),
        ),
        migrations.AddConstraint(
            model_name='objection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome__in', ['UPHELD', 'REMEDIED', 'DISMISSED']), _negated=True), ('decided_at__isnull', False), _connector='OR'), name='decided_objection_needs_date'),
        ),
        migrations.AddConstraint(
            model_name='objection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome__in', ['UPHELD', 'REMEDIED', 'DISMISSED']), _negated=True), models.Q(('decision', ''), _negated=True), _connector='OR'), name='decided_objection_needs_text'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('tender', 'seq'), name='uniq_lot_seq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcommittee',
            constraint=models.UniqueConstraint(fields=('tender', 'user'), name='uniq_member_per_tender'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcommittee',
            constraint=models.CheckConstraint(condition=models.Q(('role', ''), _negated=True), name='committee_role_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('tender', 'code'), name='uniq_criterion_code'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('tender', 'lot', 'supplier'), name='one_bid_per_bidder_per_lot'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'EVALUATED'), _negated=True), ('amount__isnull', False), _connector='OR'), name='evaluated_bid_needs_amount'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['PUBLISHED', 'CONTRACTED']), _negated=True), ('published_at__isnull', False), _connector='OR'), name='published_award_needs_date'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='approved_award_needs_date'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocument',
            constraint=models.UniqueConstraint(fields=('tender', 'kind', 'version'), name='uniq_doc_version_per_tender'),
        ),
        migrations.AddConstraint(
            model_name='partyverification',
            constraint=models.UniqueConstraint(fields=('party', 'kind'), name='uniq_verification_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='partyverification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['PASSED', 'FAILED']), ('verified_at__isnull', False)), ('status', 'PENDING'), _connector='OR'), name='passed_verification_needs_date'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['status', 'submission_close_at'], name='tender_status_close_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['agency', 'published_at'], name='tender_agency_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), _negated=True), ('est_value__isnull', True), _connector='OR'), name='draft_may_lack_estimate'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('status', 'CANCELLED'), ('est_value__isnull', False), _connector='OR'), name='published_needs_estimate'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.CheckConstraint(condition=models.Q(('budget_line__isnull', True), models.Q(('status', 'DRAFT'), _negated=True), ('budget_line__isnull', False), _connector='OR'), name='any_tender_needs_budget_line'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'AWARDED'), _negated=True), ('submission_close_at__isnull', False), _connector='OR'), name='awarded_needs_a_deadline'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('immutable_from__isnull', True)), models.Q(('published_at__isnull', False), ('immutable_from__isnull', False)), _connector='OR'), name='publish_lock_is_atomic'),
        ),
    ]
