# Generated by Django 5.2.17 on 2026-09-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tender',
            name='draft_may_lack_estimate',
        ),
        migrations.RemoveConstraint(
            model_name='tender',
            name='any_tender_needs_budget_line',
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.CheckConstraint(condition=models.Q(('budget_line__isnull', False)), name='any_tender_needs_budget_line'),
        ),
    ]
