# Generated by Django 5.2.17 on 2026-09-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_remove_tender_draft_may_lack_estimate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tender',
            name='publish_lock_is_atomic',
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('published_at__isnull', False), _connector='OR'), name='non_draft_needs_published_at'),
        ),
    ]
