# Generated by Django 5.2.17 on 2026-09-20 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_remove_tender_publish_lock_is_atomic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
