# Generated by Django 5.2.17 on 2026-09-21 08:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_award_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='defects_liability_end',
            field=models.DateTimeField(blank=True, help_text='End of defects liability period (signed_at + defect_days)', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='retention_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Retention money percentage held until defects liability ends', max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='retention_released',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount of retention money released', max_digits=14),
        ),
        migrations.AddField(
            model_name='party',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Performance score out of 100, updated on contract close-out', max_digits=5),
        ),
        migrations.AddField(
            model_name='party',
            name='total_contracts_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
