# Generated by Django 5.2.17 on 2026-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_drop_duplicate_catalogue_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyverification',
            name='kind',
            field=models.CharField(choices=[('CAC', 'Corporate affairs (CAC registry)'), ('TIN', 'Tax identification (FIRS)'), ('PENSION', 'PenCom certificate'), ('ITF', 'Industrial Training Fund compliance'), ('NSITF', 'NSITF employee-compensation compliance'), ('BANK', 'NUBAN account-name match'), ('BO', 'Beneficial ownership'), ('DEBARMENT', 'Debarment/exclusion screening'), ('CAPABILITY', 'Technical and financial capability')], max_length=12),
        ),
    ]
