# Generated by Django 5.2.17 on 2026-09-20 19:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0004_alter_award_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_sha256', models.CharField(max_length=64)),
                ('report_obj_key', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final', models.BooleanField(default=False)),
                ('recommended_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.bid')),
                ('signed_by', models.ManyToManyField(to='procurement.evaluationcommittee')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_recommendation',
            },
        ),
        migrations.CreateModel(
            name='CategoryWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Category A — Works (major)'), ('B', 'Category B — Goods'), ('C', 'Category C — Services / consultancy'), ('D', 'Category D — ICT')], max_length=1)),
                ('mda_code', models.CharField(blank=True, max_length=12)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_watches', to='procurement.party')),
            ],
            options={
                'db_table': 'proc_category_watch',
            },
        ),
        migrations.CreateModel(
            name='ClarificationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_official', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('visible_to_bidders', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clar_posts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='procurement.tenderquestion')),
            ],
            options={
                'db_table': 'proc_clar_post',
                'ordering': ['posted_at'],
            },
        ),
        migrations.CreateModel(
            name='DissentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissents', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissents', to='procurement.score')),
            ],
            options={
                'db_table': 'proc_dissent',
            },
        ),
        migrations.CreateModel(
            name='MFASession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('TOTP', 'Authenticator app (TOTP)'), ('SMS', 'SMS OTP')], max_length=4)),
                ('otp_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_mfa_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('sha256', models.CharField(max_length=64)),
                ('obj_key', models.CharField(max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confidential', models.BooleanField(default=False, help_text='withheld from public publication per whistleblower protection')),
                ('objection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='procurement.objection')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proc_objection_evidence',
            },
        ),
        migrations.CreateModel(
            name='ObjectionPanelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nominator', models.CharField(choices=[('GOV', 'Government'), ('CSO', 'Civil society')], max_length=8)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('objection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='procurement.objection')),
            ],
            options={
                'db_table': 'proc_panelist',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('specification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('awarded_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('QUOTING', 'Quoting'), ('AWARDED', 'Awarded'), ('ACCEPTED', 'Accepted'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='QUOTING', max_length=16)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.agency')),
                ('awarded_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_awards', to='procurement.party')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.budgetline')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cat_po',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField(help_text='Fernet-encrypted JSON payload, base64')),
                ('ciphertext_sha256', models.CharField(max_length=64)),
                ('ciphertext_size', models.PositiveBigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('resume_offsets', models.JSONField(default=list, help_text='resumable upload chunk offsets')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('unsealed_at', models.DateTimeField(blank=True, null=True)),
                ('unsealed_plaintext_sha256', models.CharField(blank=True, max_length=64)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envelope', to='procurement.bid')),
            ],
            options={
                'db_table': 'proc_submission',
            },
        ),
        migrations.CreateModel(
            name='SupplierRegistrationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.PositiveSmallIntegerField(choices=[(1, 'Company identity'), (2, 'Contact person'), (3, 'Certificates'), (4, 'Capability & classification'), (5, 'Beneficial ownership & declarations'), (6, 'Review & submit')], default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFYING', 'Verifying'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('company_name', models.CharField(blank=True, max_length=250)),
                ('rc_number', models.CharField(blank=True, max_length=20)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('pencom', models.CharField(blank=True, max_length=40)),
                ('year_incorporated', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('state', models.CharField(default='Taraba', max_length=40)),
                ('lga', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('A', 'Category A — Works (major)'), ('B', 'Category B — Goods'), ('C', 'Category C — Services / consultancy'), ('D', 'Category D — ICT')], max_length=1)),
                ('scope', models.CharField(choices=[('LOCAL', 'Taraba-domiciled'), ('NATIONAL', 'Nigerian, outside Taraba')], default='LOCAL', max_length=8)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('similar_contracts_n', models.PositiveIntegerField(default=0)),
                ('annual_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('related_party_declaration', models.TextField(blank=True)),
                ('accept_terms', models.BooleanField(default=False)),
                ('pep_flag', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submitted_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='procurement.party')),
            ],
            options={
                'db_table': 'vendor_draft',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_key_b64', models.BinaryField()),
                ('wrapped_shares', models.JSONField(default=dict)),
                ('public_keys', models.JSONField(default=dict)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_by', models.JSONField(default=list)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sealing', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_tender_key',
            },
        ),
        migrations.CreateModel(
            name='TranslationString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('language', models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('tiv', 'Tiv'), ('wuk', 'Wukari')], db_index=True, max_length=6)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'i18n_string',
                'constraints': [models.UniqueConstraint(fields=('key', 'language'), name='uniq_i18n_key')],
            },
        ),
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lang_pref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'i18n_user_pref',
            },
        ),
        migrations.CreateModel(
            name='WhistleblowerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(editable=False, max_length=16, unique=True)),
                ('tender_ocid', models.CharField(blank=True, max_length=60)),
                ('body_ciphertext', models.TextField(help_text="encrypted with the reporter's one-time key")),
                ('contact_hash', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('TRIAGED', 'Triaged'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='RECEIVED', max_length=16)),
                ('triage_notes', models.TextField(blank=True, help_text='internal, not published')),
                ('outcome_published', models.TextField(blank=True, help_text='published outcome summary')),
                ('outcome_published_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wb_report',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('sku', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('tax_inclusive', models.BooleanField(default=True)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_image_sha256', models.CharField(blank=True, max_length=64)),
                ('spec_hash', models.CharField(blank=True, max_length=64)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_items', to='procurement.party')),
            ],
            options={
                'db_table': 'cat_item',
                'indexes': [models.Index(fields=['category', 'is_active', 'unit_price'], name='cat_price_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'sku'), name='uniq_sku_per_supplier')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=24)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('USSD', 'USSD push'), ('INAPP', 'In-app')], max_length=8)),
                ('kind', models.CharField(choices=[('BID_RECEIVED', 'Bid submission receipt'), ('TENDER_PUBLISHED', 'New tender matching alert'), ('ADDENDUM', 'Addendum published'), ('DEADLINE', 'Deadline reminder'), ('AWARD', 'Award notice'), ('OBJECTION', 'Objection status'), ('REG_OK', 'Supplier registration approved'), ('REG_NO', 'Supplier registration rejected'), ('MFA', 'MFA code'), ('WB', 'Whistleblower reference')], max_length=16)),
                ('body', models.TextField()),
                ('reference_key', models.CharField(blank=True, max_length=64)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notif_outbox',
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['channel', 'scheduled_for', 'sent_at'], name='notif_pending_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogueQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('lead_time_days', models.PositiveSmallIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_l1', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.party')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='workflow.purchaseorder')),
            ],
            options={
                'db_table': 'cat_quote',
                'constraints': [models.UniqueConstraint(fields=('po', 'supplier'), name='uniq_quote_per_supplier')],
            },
        ),
        migrations.CreateModel(
            name='DraftOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=250)),
                ('owner_rc', models.CharField(blank=True, max_length=20)),
                ('owner_nin_hash', models.CharField(blank=True, help_text='SHA-256 of NIN; NIN never stored cleartext', max_length=64)),
                ('pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_pep', models.BooleanField(default=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='workflow.supplierregistrationdraft')),
            ],
            options={
                'db_table': 'vendor_draft_owner',
                'constraints': [models.CheckConstraint(condition=models.Q(('pct__gt', Decimal('0')), ('pct__lte', Decimal('100'))), name='owner_pct_range_draft')],
            },
        ),
        migrations.CreateModel(
            name='DraftDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CAC', 'CAC incorporation certificate'), ('TIN', 'TIN / tax clearance'), ('PENCOM', 'PenCom compliance certificate'), ('BANK', 'Bank reference / NUBAN verification'), ('TECH', 'Technical capability memo')], max_length=8)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('obj_key', models.CharField(max_length=300)),
                ('filename', models.CharField(max_length=240)),
                ('content_type', models.CharField(default='application/pdf', max_length=80)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('verification_note', models.TextField(blank=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workflow.supplierregistrationdraft')),
            ],
            options={
                'db_table': 'vendor_draft_document',
                'constraints': [models.UniqueConstraint(fields=('draft', 'kind'), name='uniq_doc_kind_per_draft')],
            },
        ),
        migrations.CreateModel(
            name='TenderWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_watches', to='procurement.party')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_watch',
                'constraints': [models.UniqueConstraint(fields=('party', 'tender'), name='uniq_watch')],
            },
        ),
    ]
