# Generated by Django 5.2.17 on 2026-09-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('USSD', 'USSD push'), ('IN_APP', 'In-app')], max_length=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('BID_RECEIVED', 'Bid submission receipt'), ('TENDER_PUBLISHED', 'New tender matching alert'), ('ADDENDUM', 'Addendum published'), ('DEADLINE', 'Deadline reminder'), ('AWARD', 'Award notice'), ('OBJECTION', 'Objection status'), ('REG_OK', 'Supplier registration approved'), ('REG_NO', 'Supplier registration rejected'), ('MFA', 'MFA code'), ('WB', 'Whistleblower reference'), ('IN_APP', 'In-app notification')], max_length=16),
        ),
    ]
