# Generated by Django 5.2.17 on 2026-09-21 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_award_approved_by'),
        ('workflow', '0002_alter_notification_channel_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_body', models.CharField(choices=[('AO', 'Accounting Officer / Perm Sec'), ('MTB', 'Ministerial Tenders Board'), ('BPP', 'BPP No-Objection Certificate'), ('SEC', 'State Executive Council'), ('FEC', 'Federal Executive Council')], max_length=4)),
                ('required_reason', models.CharField(blank=True, max_length=300)),
                ('approved_by_body', models.CharField(blank=True, choices=[('AO', 'Accounting Officer / Perm Sec'), ('MTB', 'Ministerial Tenders Board'), ('BPP', 'BPP No-Objection Certificate'), ('SEC', 'State Executive Council'), ('FEC', 'Federal Executive Council')], max_length=4)),
                ('approval_ref', models.CharField(blank=True, max_length=80)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=True, help_text='Approval matches threshold rules')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_routing', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_approval_routing',
            },
        ),
        migrations.CreateModel(
            name='BidReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('pdf_obj_key', models.CharField(blank=True, max_length=300)),
                ('signature', models.CharField(help_text='HMAC signature for verification', max_length=120)),
                ('verification_url', models.CharField(blank=True, max_length=300)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_doc', to='procurement.bid')),
            ],
            options={
                'db_table': 'proc_bid_receipt',
            },
        ),
        migrations.CreateModel(
            name='CommitteeDissent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissents_overall', to='procurement.evaluationcommittee')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissents', to='workflow.awardrecommendation')),
            ],
            options={
                'db_table': 'proc_committee_dissent',
            },
        ),
        migrations.CreateModel(
            name='ContractGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ADVANCE', 'Advance payment guarantee'), ('PERFORMANCE', 'Performance guarantee'), ('RETENTION', 'Retention money'), ('WARRANTY', 'Warranty bond')], max_length=12)),
                ('issuer', models.CharField(help_text='Bank or insurance company', max_length=200)),
                ('reference', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('document_sha256', models.CharField(blank=True, max_length=64)),
                ('document_obj_key', models.CharField(blank=True, max_length=300)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('released_note', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='procurement.contract')),
            ],
            options={
                'db_table': 'proc_guarantee',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('DELIVERED', 'Delivered, pending inspection'), ('ACCEPTED', 'Inspected and accepted'), ('REJECTED', 'Inspected and rejected'), ('OVERDUE', 'Past due date')], default='PLANNED', max_length=12)),
                ('inspection_note', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='procurement.contract')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones_inspected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proc_milestone',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='ContractVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('reason', models.TextField()),
                ('amount_change', models.DecimalField(decimal_places=2, max_digits=18)),
                ('time_change_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=12)),
                ('proposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('alarm_triggered', models.BooleanField(default=False, help_text='Variation >10% of signed value')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations_approved', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='procurement.contract')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations_proposed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proc_variation',
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='DebriefRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_by', models.DateTimeField(help_text='10 working days from request')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue (>10 working days)')], default='REQUESTED', max_length=12)),
                ('questions', models.TextField(blank=True, help_text='Specific questions from the losing bidder')),
                ('response', models.TextField(blank=True, help_text='Written debrief response, published')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=True, help_text='Debrief response is public')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debriefs', to='procurement.award')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debriefs_given', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debrief_requests', to='procurement.party')),
            ],
            options={
                'db_table': 'proc_debrief',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_sha256', models.CharField(max_length=64)),
                ('report_obj_key', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(help_text='Executive summary, published verbatim')),
                ('methodology', models.TextField(blank=True, help_text='How scores were computed')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=True)),
                ('signed_by_count', models.PositiveSmallIntegerField(default=0)),
                ('dissents_count', models.PositiveSmallIntegerField(default=0)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval_report', to='procurement.tender')),
            ],
            options={
                'db_table': 'proc_evaluation_report',
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='procurement.contract')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='workflow.contractmilestone')),
                ('payment_cert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='procurement.paymentcertification')),
            ],
            options={
                'db_table': 'proc_payment_schedule',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformanceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Satisfactory'), ('D', 'Poor'), ('F', 'Defaulted')], max_length=1)),
                ('timeliness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('variation_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('composite', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('narrative', models.TextField(blank=True, help_text='Published rationale for the grade')),
                ('rated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='procurement.contract')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='procurement.party')),
            ],
            options={
                'db_table': 'proc_performance_rating',
            },
        ),
        migrations.AddConstraint(
            model_name='contractmilestone',
            constraint=models.UniqueConstraint(fields=('contract', 'seq'), name='uniq_milestone_seq'),
        ),
        migrations.AddConstraint(
            model_name='debriefrequest',
            constraint=models.UniqueConstraint(fields=('award', 'supplier'), name='uniq_debrief_per_supplier_per_award'),
        ),
        migrations.AddConstraint(
            model_name='debriefrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('responded_at__isnull', False), _connector='OR'), name='completed_debrief_needs_response_date'),
        ),
    ]
