# Generated by Django 5.2.17 on 2026-09-21 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_phases_2_3_4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhistleblowerCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('encrypted_content', models.TextField(help_text='AES-256 encrypted report content')),
                ('content_hash', models.CharField(help_text='SHA256 hash of encrypted content for integrity verification', max_length=64)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whistleblower_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whistleblower Case',
                'verbose_name_plural': 'Whistleblower Cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
