# Generated by Django 5.2.17 on 2026-09-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_whistleblowercase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhistleblowerCase',
        ),
    ]
