# Generated by Django 5.2.17 on 2026-09-21 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_partyverification_kind'),
        ('workflow', '0005_delete_whistleblowercase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draftdocument',
            name='blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierregistrationdraft',
            name='employees_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Staff on the payroll. Drives the statutory exemptions: PenCom does not apply below 3 employees (Pension Reform Act 2014), ITF below 5.', null=True),
        ),
        migrations.AddField(
            model_name='supplierregistrationdraft',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text='Public reference, e.g. VND-000042', max_length=16),
        ),
        migrations.AlterField(
            model_name='draftdocument',
            name='kind',
            field=models.CharField(choices=[('CAC', 'CAC incorporation certificate'), ('TIN', 'TIN / tax clearance'), ('PENCOM', 'PenCom compliance certificate'), ('ITF', 'ITF compliance certificate'), ('NSITF', 'NSITF compliance certificate'), ('BANK', 'Bank reference / NUBAN verification'), ('TECH', 'Technical capability memo')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='supplierregistrationdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('reference',), name='uniq_vendor_draft_reference'),
        ),
    ]
