# Generated by Django 5.2.17 on 2026-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('aggregate', models.CharField(db_index=True, editable=False, max_length=160)),
                ('event_type', models.CharField(db_index=True, editable=False, max_length=80)),
                ('actor', models.CharField(editable=False, help_text="username, or 'anonymous' / 'system'", max_length=120)),
                ('payload', models.JSONField(editable=False)),
                ('occurred_at', models.DateTimeField(db_index=True, editable=False)),
                ('prev_hash', models.CharField(editable=False, max_length=64)),
                ('row_hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'ledger event',
                'verbose_name_plural': 'ledger events',
                'db_table': 'ledger_event',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['aggregate', 'seq'], name='ledger_aggregate_seq_idx'), models.Index(fields=['event_type', 'occurred_at'], name='ledger_type_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('payload', {}), _negated=True), name='event_payload_not_empty'), models.CheckConstraint(condition=models.Q(('seq', 0), _negated=True), name='event_seq_nonzero')],
            },
        ),
    ]
